[package]
name = "migrations_macros"
version = "1.4.0"
authors = ["Sean Griffin <sean@seantheprogrammer.com>"]
license = "MIT OR Apache-2.0"
description = "Codegeneration macros for diesels embedded migrations"
documentation = "http://docs.diesel.rs"
homepage = "http://diesel.rs"

[dependencies]
migrations_internals = "~1.4.0"
syn = { version = "0.15", features = ["extra-traits"] }
quote = "0.6"
proc-macro2 = "0.4"

[dev-dependencies]
tempdir = "0.3.4"

[lib]
proc-macro = true

[features]
default = []
