[package]
name = "migrations_macros"
version = "1.4.1"
authors = ["Sean Griffin <sean@seantheprogrammer.com>"]
license = "MIT OR Apache-2.0"
description = "Codegeneration macros for diesels embedded migrations"
documentation = "https://docs.diesel.rs"
homepage = "https://diesel.rs"

[dependencies]
syn = { version = "1", features = ["extra-traits"] }
quote = "1"
proc-macro2 = "1"

[dependencies.migrations_internals]
version = "~1.4.0"
path = "../migrations_internals"

[dev-dependencies]
tempfile = "3.0.0"

[lib]
proc-macro = true

[features]
default = []
