[package]
name = "migrations_macros"
version = "2.2.0"
license = "MIT OR Apache-2.0"
description = "Codegeneration macros for diesels embedded migrations"
homepage = "https://diesel.rs"
repository = "https://github.com/diesel-rs/diesel"
edition = "2021"
include.workspace = true
rust-version.workspace = true

[dependencies]
quote = "1"
proc-macro2 = "1"

[dependencies.migrations_internals]
version = "~2.2.0"
path = "../migrations_internals"

[dev-dependencies]
tempfile = "3.1.0"
dotenvy = "0.15"
cfg-if = "1.0.0"

[dev-dependencies.diesel]
path = "../../diesel"
default-features = false

[dev-dependencies.diesel_migrations]
path = "../"
default-features = false

[lib]
proc-macro = true

[features]
default = []
sqlite = []
postgres = []
mysql = []
