[files]
extend-exclude = [
    ".git/",
    "diesel_compile_tests/**/*.stderr",
]
ignore-hidden = false

[default]
extend-ignore-re = [
    # That's a ipv6
    "2001:4f8:3:ba",
    # That is just strangely cased
    "dO_nOt_cHaNgE_cAsE", "fOoBaR",
    # That is the name of a book author
    "michael_ende", "Michael Ende",
    # That's an actual money unit (include the comment to only match that part)
    "use diesel::data_types::PgMoney as Fils; // 1/1000th unit of Dinar",
    # That's a name (include the expression to only match the relevant part)
    "name\\.eq\\(\"Claus\"\\)",
    # Thats a test for a typo,
    "cannot find value `titel` in module `posts`",
    "cannot find type `titel` in module `posts`",
    "[0-9]+[[:space]]+|[[:space:]]+titel: String",
    "big_sur",
    # That's Spanish for "type" (used in a unit-test)
    "tipe",
    # we use this often in place of the reserved type identifier
    "tpe",
]

[type.md]
extend-ignore-re = [
    # Occurs in the changelog
    "derive\\(Queriable\\)", "`Queriable`"
]
