[workspace]
members = [
    "diesel",
    "diesel_cli",
    "diesel_derives",
    # FIXME: getting "multiple matching crates for `diesel`" because of the shared build directory
    # "diesel_compile_tests",
    "diesel_tests",
    "diesel_migrations",
    "diesel_migrations/migrations_internals",
    "diesel_migrations/migrations_macros",
    "examples/mysql/all_about_inserts",
    "examples/mysql/getting_started_step_1",
    "examples/mysql/getting_started_step_2",
    "examples/mysql/getting_started_step_3",
    "examples/postgres/advanced-blog-cli",
    "examples/postgres/all_about_inserts",
    "examples/postgres/all_about_updates",
    "examples/postgres/getting_started_step_1",
    "examples/postgres/getting_started_step_2",
    "examples/postgres/getting_started_step_3",
    "examples/sqlite/all_about_inserts",
    "examples/sqlite/getting_started_step_1",
    "examples/sqlite/getting_started_step_2",
    "examples/sqlite/getting_started_step_3",
]

[replace]
"diesel:1.4.2" = { path = "diesel" }
"diesel_derives:1.4.0" = { path = "diesel_derives" }
"diesel_migrations:1.4.0" = { path = "diesel_migrations" }
"migrations_internals:1.4.0" = { path = "diesel_migrations/migrations_internals" }
"migrations_macros:1.4.0" = { path = "diesel_migrations/migrations_macros" }
