[workspace]
members = ["cargo:."]

# Config for 'dist'
[dist]
# The preferred dist version to use in CI (Cargo.toml SemVer syntax)
cargo-dist-version = "0.30.3"
# CI backends to support
ci = "github"
# The installers to generate for each app
installers = ["shell", "powershell"]
# Target platforms to build apps for (Rust target-triple syntax)
targets = ["aarch64-apple-darwin", "aarch64-unknown-linux-gnu", "x86_64-apple-darwin", "x86_64-unknown-linux-gnu", "x86_64-pc-windows-msvc"]
# Which actions to run on pull requests
pr-run-mode = "upload"
# Whether dist should create a Github Release or use an existing draft
create-release = false
# Whether to install an updater program
install-updater = false
# Path that installers should place binaries in
install-path = "CARGO_HOME"
# Whether to use cargo-cyclonedx to generate an SBOM
cargo-cyclonedx = true
# Whether to enable GitHub Attestations
github-attestations = true

[dist.min-glibc-version]
"*" = "2.17"

[dist.dependencies.apt]
libncurses5-dev = '*'
libtirpc-dev = '*'

# otherwise the builds fail for whatever reason
[dist.github-custom-runners]
x86_64-apple-darwin = "macos-15-intel"
aarch64-apple-darwin = "macos-15"
aarch64-unknown-linux-gnu = "ubuntu-22.04-arm"
