[package]
name = "advanced-blog-cli"
version = "0.1.0"
edition = "2018"
publish = false

[dependencies]
argon2 = "0.5.0"
chrono = { version = "0.4.20", default-features = false, features = ["clock", "std"] }
diesel = { version = "2.1.0", path = "../../../diesel", features = ["postgres", "chrono"] }
dotenvy = "0.15"
clap = { version = "4.2.7", features = ["derive"] }
tempfile = "3.1.0"

[dev-dependencies]
assert_matches = "1.1"
diesel_migrations = { features = ["postgres"], path = "../../../diesel_migrations" }
lazy_static = "1.0"

[[bin]]
name = "advanced-blog-cli"
path = "src/main.rs"
doc = false
