[package]
name = "advanced-blog-cli"
version = "0.1.0"
edition = "2018"
publish = false

[dependencies]
bcrypt = "0.10.1"
chrono = { version = "0.4.19", default-features = false, features = ["clock", "std"] }
diesel = { version = "2.0.0", path = "../../../diesel", features = ["postgres", "chrono"] }
dotenvy = "0.15"
structopt = "0.3"
tempfile = "3.1.0"

[dev-dependencies]
assert_matches = "1.1"
diesel_migrations = { version = "2.0.0", features = ["postgres"], path = "../../../diesel_migrations" }
lazy_static = "1.0"

[[bin]]
name = "advanced-blog-cli"
path = "src/main.rs"
doc = false
