[package]
name = "advanced-blog-cli"
version = "0.1.0"
authors = ["Sean Griffin <sean@seantheprogrammer.com>"]
edition = "2018"

[dependencies]
bcrypt = "0.1.0"
chrono = "0.4.0"
diesel = { version = "2.0.0", path = "../../../diesel", features = ["postgres", "chrono"] }
dotenv = "0.15"
structopt = "0.1.6"
structopt-derive = "0.1.6"
tempfile = "2.2.0"

[dev-dependencies]
assert_matches = "1.1"
diesel_migrations = { version = "1.4.0", features = ["postgres"], path = "../../../diesel_migrations" }
lazy_static = "1.0"
