[package]
name = "all_about_updates"
version = "0.1.0"
authors = ["Sage Griffin <sean@seantheprogrammer.com>"]
edition = "2018"

[dependencies]
diesel = { version = "2.0.0-rc.0", path = "../../../diesel", features = ["postgres"] }

[lib]
doc = false
