[package]
name = "all_about_updates"
version = "0.1.0"
authors = ["Sean Griffin <sean@seantheprogrammer.com>"]

[dependencies]
diesel = { version = "0.15.0", features = ["postgres"] }
diesel_codegen = "0.15.0"
