[package]
name = "diesel_derives"
version = "1.1.0"
authors = ["Sean Griffin <sean@seantheprogrammer.com>"]
license = "MIT OR Apache-2.0"
readme = "README.md"
documentation = "https://diesel.rs/guides/"
homepage = "https://diesel.rs"
repository = "https://github.com/diesel-rs/diesel/tree/master/diesel_derives"

[dependencies]
syn = { version = "0.11.4", features = ["aster"] }
quote = "0.3.12"
clippy = { optional = true, version = "=0.0.185" }

[dev-dependencies]
dotenv = { version = ">=0.8, <0.11", default-features = false }
tempdir = "0.3.4"
diesel = { version = "1.1.0", default-features = false }
cfg-if = "0.1.0"

[lib]
proc-macro = true

[features]
default = []
lint = ["clippy"]
postgres = []
sqlite = []
mysql = []

[badges]
travis-ci = { repository = "diesel-rs/diesel" }
appveyor = { repository = "diesel-rs/diesel" }
