[package]
name = "diesel_derives"
version = "1.2.0"
authors = ["Sean Griffin <sean@seantheprogrammer.com>"]
license = "MIT OR Apache-2.0"
description = "You should not use this crate directly, it is internal to Diesel."
documentation = "https://diesel.rs/guides/"
homepage = "https://diesel.rs"
repository = "https://github.com/diesel-rs/diesel/tree/master/diesel_derives"

[dependencies]
syn = { version = "0.13.0", features = ["full", "fold"] }
quote = "0.5.0"
clippy = { optional = true, version = "=0.0.195" }
proc-macro2 = "0.3.0"

[dev-dependencies]
cfg-if = "0.1.0"
diesel = "1.2.0"
dotenv = "0.10.0"

[lib]
proc-macro = true

[[test]]
name = "tests"

[features]
default = []
lint = ["clippy"]
nightly = ["proc-macro2/nightly"]
postgres = []
sqlite = []
mysql = []

[badges]
travis-ci = { repository = "diesel-rs/diesel" }
appveyor = { repository = "diesel-rs/diesel" }
