[package]
name = "diesel_derives"
version = "0.16.0"
authors = ["Sean Griffin <sean@seantheprogrammer.com>"]
license = "MIT OR Apache-2.0"
description = "Custom derive and procedural macros for Diesel"
readme = "README.md"
documentation = "https://diesel.rs/guides/"
homepage = "https://diesel.rs"
repository = "https://github.com/diesel-rs/diesel/tree/master/diesel_derives"
keywords = ["orm", "database", "postgres", "sql", "codegen"]

[dependencies]
syn = { version = "0.11.4", features = ["aster"] }
quote = "0.3.12"
clippy = { optional = true, version = "=0.0.162" }

[dev-dependencies]
dotenv = { version = ">=0.8, <0.11", default-features = false }
tempdir = "0.3.4"
diesel = { version = "0.16", features = ["sqlite", "postgres", "mysql"] }
cfg-if = "0.1.0"

[lib]
proc-macro = true

[features]
default = []
lint = ["clippy"]
postgres = []
sqlite = []
mysql = []

[[test]]
name = "tests"

[badges]
travis-ci = { repository = "diesel-rs/diesel" }
appveyor = { repository = "sgrif/diesel" }
