[package]
name = "diesel_derives"
version = "2.0.0-rc.1"
license = "MIT OR Apache-2.0"
description = "You should not use this crate directly, it is internal to Diesel."
documentation = "https://diesel.rs/guides/"
homepage = "https://diesel.rs"
repository = "https://github.com/diesel-rs/diesel/tree/master/diesel_derives"
autotests = false
include = ["src/**/*", "LICENSE-*"]
rust-version = "1.56.0"

[dependencies]
syn = { version = "1.0.73", features = ["derive", "fold"] }
quote = "1.0.9"
proc-macro2 = "1.0.27"
proc-macro-error = "1.0.4"

[dev-dependencies]
cfg-if = "1"
dotenvy = "0.15"

[dev-dependencies.diesel]
version = "~2.0.0-rc.1"
path = "../diesel"

[lib]
proc-macro = true

[[test]]
name = "tests"

[features]
default = []
nightly = ["proc-macro2/nightly"]
postgres = []
sqlite = []
mysql = []
32-column-tables = []
64-column-tables = ["32-column-tables"]
128-column-tables = ["64-column-tables"]
without-deprecated = []
with-deprecated = []
