[package]
name = "diesel_migrations"
version = "1.2.0"
authors = ["Sean Griffin <sean@seantheprogrammer.com>"]
license = "MIT OR Apache-2.0"
description = "Migration management for diesel"
documentation = "https://docs.rs/crate/diesel_migrations"
homepage = "http://diesel.rs"


[dependencies]
clippy = { optional = true, version = "=0.0.195" }
migrations_internals = "~1.2.0"
migrations_macros = "~1.2.0"

[dev-dependencies]
diesel = { version = "1.2.0", default-features = false, features = ["sqlite", "postgres", "mysql"] }
dotenv = ">=0.8, <0.11"
cfg-if = "0.1.0"

[features]
default = []
lint = ["clippy"]
sqlite = []
postgres = []
mysql = []
