[package]
name = "diesel"
version = "0.16.0"
authors = ["Sean Griffin <sean@seantheprogrammer.com>"]
license = "MIT OR Apache-2.0"
description = "A safe, extensible ORM and Query builder"
readme = "README.md"
documentation = "http://docs.diesel.rs"
homepage = "http://diesel.rs"
repository = "https://github.com/diesel-rs/diesel"
keywords = ["orm", "database", "postgres", "postgresql", "sql"]
categories = ["database"]

[dependencies]
byteorder = "1.0"
chrono = { version = "0.4", optional = true }
clippy = { optional = true, version = "=0.0.162" }
libc = { version = "0.2.0", optional = true }
libsqlite3-sys = { version = ">=0.8.0, <0.9.0", optional = true, features = ["min_sqlite_version_3_7_16"] }
mysqlclient-sys = { version = ">=0.1.0, <0.3.0", optional = true }
pq-sys = { version = ">=0.3.0, <0.5.0", optional = true }
quickcheck = { version = "0.3.1", optional = true }
serde_json = { version = ">=0.8.0, <2.0", optional = true }
time = { version = "0.1", optional = true }
url = { version = "1.4.0", optional = true }
uuid = { version = ">=0.2.0, <0.6.0", optional = true, features = ["use_std"] }
ipnetwork = { version = "0.12.2", optional = true }
num-bigint = { version = "0.1.37", optional = true }
num-traits = { version = "0.1.35", optional = true }
num-integer = { version = "0.1.32", optional = true }
bigdecimal = { version = "0.0.10", optional = true }
bitflags = { version = "0.9", optional = true }

[dev-dependencies]
cfg-if = "0.1.0"
diesel_codegen = "0.16.0"
dotenv = ">=0.8, <0.11"
quickcheck = "0.3.1"
tempdir = "^0.3.4"

[features]
default = ["with-deprecated"]
extras = ["chrono", "serde_json", "uuid", "deprecated-time", "network-address", "numeric"]
unstable = []
lint = ["clippy"]
large-tables = []
huge-tables = ["large-tables"]
postgres = ["pq-sys", "bitflags"]
sqlite = ["libsqlite3-sys"]
mysql = ["mysqlclient-sys", "url"]
with-deprecated = []
deprecated-time = ["time"]
network-address = ["ipnetwork", "libc"]
numeric = ["num-bigint", "bigdecimal", "num-traits", "num-integer"]

[badges]
travis-ci = { repository = "diesel-rs/diesel" }
appveyor = { repository = "sgrif/diesel" }

[package.metadata.docs.rs]
features = ["postgres", "mysql", "sqlite", "extras"]
no-default-features = true
