[package]
name = "diesel"
version = "2.0.0"
authors = ["Sean Griffin <sean@seantheprogrammer.com>"]
license = "MIT OR Apache-2.0"
description = "A safe, extensible ORM and Query Builder for PostgreSQL, SQLite, and MySQL"
readme = "README.md"
documentation = "https://docs.rs/diesel/"
homepage = "https://diesel.rs"
repository = "https://github.com/diesel-rs/diesel"
keywords = ["orm", "database", "blockchain", "sql"]
categories = ["database"]
edition = "2018"

[dependencies]
byteorder = "1.0"
bytes = {version = "0.5", optional = true}
chrono = { version = "0.4.19", optional = true, default-features = false, features = ["clock", "std"] }
libc = { version = "0.2.0", optional = true }
libsqlite3-sys = { version = ">=0.8.0, <0.23.0", optional = true, features = ["min_sqlite_version_3_7_16"] }
mysqlclient-sys = { version = "0.2.0", optional = true }
postgresql = {version = "0.19", optional = true, package = "postgres" }
quickcheck = { version = "0.9.0", optional = true }
serde_json = { version = ">=0.8.0, <2.0", optional = true }
url = { version = "2.1.0", optional = true }
percent-encoding = { version = "2.1.0", optional = true }
uuid = { version = ">=0.7.0, <0.9.0", optional = true}
ipnetwork = { version = ">=0.12.2, <0.19.0", optional = true }
num-bigint = { version = ">=0.2.0, <0.4.0", optional = true }
num-traits = { version = "0.2.0", optional = true }
num-integer = { version = "0.1.39", optional = true }
bigdecimal = { version = ">=0.0.13, < 0.3.0", optional = true }
bitflags = { version = "1.2.0", optional = true }
r2d2 = { version = ">= 0.8.0, < 0.9.0", optional = true }
itoa = "0.4.0"

[dependencies.diesel_derives]
version = "~2.0.0"
path = "../diesel_derives"

[dev-dependencies]
cfg-if = "1"
dotenv = "0.15"
ipnetwork = ">=0.12.2, <0.19.0"
quickcheck = "0.9"

[features]
default = ["with-deprecated", "32-column-tables"]
extras = ["chrono", "serde_json", "uuid", "network-address", "numeric", "r2d2"]
unstable = ["diesel_derives/nightly"]
large-tables = ["32-column-tables"]
huge-tables = ["64-column-tables"]
32-column-tables = []
64-column-tables = ["32-column-tables"]
128-column-tables = ["64-column-tables"]
postgres = ["bitflags", "bytes", "diesel_derives/postgres", "postgresql"]
sqlite = ["libsqlite3-sys", "diesel_derives/sqlite"]
mysql = ["mysqlclient-sys", "url", "percent-encoding", "diesel_derives/mysql", "bitflags"]
without-deprecated = []
with-deprecated = []
network-address = ["ipnetwork", "libc"]
numeric = ["num-bigint", "bigdecimal", "num-traits", "num-integer"]

[package.metadata.docs.rs]
features = ["postgres", "mysql", "sqlite", "extras"]
no-default-features = true
