[package]
name = "diesel"
version = "0.12.0"
authors = ["Sean Griffin <sean@seantheprogrammer.com>"]
license = "MIT OR Apache-2.0"
description = "A safe, extensible ORM and Query builder"
readme = "README.md"
documentation = "http://docs.diesel.rs"
homepage = "http://diesel.rs"
repository = "https://github.com/diesel-rs/diesel"
keywords = ["orm", "database", "postgres", "postgresql", "sql"]
categories = ["database"]

[dependencies]
byteorder = "1.0"
chrono = { version = "0.3", optional = true }
clippy = { optional = true, version = "=0.0.118" }
libsqlite3-sys = { version = ">=0.7.1, <0.8.0", optional = true }
mysqlclient-sys = { version = ">=0.1.0, <0.3.0", optional = true }
pq-sys = { version = ">=0.3.0, <0.5.0", optional = true }
quickcheck = { version = "0.3.1", optional = true }
serde_json = { version = ">=0.8.0, <0.10.0", optional = true }
time = { version = "0.1", optional = true }
url = { version = "1.4.0", optional = true }
uuid = { version = ">=0.2.0, <0.5.0", optional = true, features = ["use_std"] }

[dev-dependencies]
cfg-if = "0.1.0"
diesel_codegen = "0.12.0"
dotenv = ">=0.8, <0.10"
quickcheck = "0.3.1"
tempdir = "^0.3.4"

[features]
default = ["with-deprecated"]
extras = ["chrono", "serde_json", "uuid", "deprecated-time"]
unstable = []
lint = ["clippy"]
large-tables = []
huge-tables = ["large-tables"]
postgres = ["pq-sys"]
sqlite = ["libsqlite3-sys"]
mysql = ["mysqlclient-sys", "url"]
with-deprecated = []
deprecated-time = ["time"]

[badges]
travis-ci = { repository = "diesel-rs/diesel" }
appveyor = { repository = "sgrif/diesel" }
