[package]
name = "diesel"
version = "0.10.0"
authors = ["Sean Griffin <sean@seantheprogrammer.com>"]
license = "MIT OR Apache-2.0"
description = "A safe, extensible ORM and Query builder"
documentation = "http://docs.diesel.rs"
homepage = "http://diesel.rs"
repository = "https://github.com/diesel-rs/diesel"
keywords = ["orm", "database", "postgres", "postgresql", "sql"]
categories = ["database"]

[dependencies]
byteorder = "1.0"
chrono = { version = "^0.2.17", optional = true }
libc = "0.2.*"
libsqlite3-sys = { version = ">= 0.4.0, <0.7.0", optional = true }
mysqlclient-sys = { git = "https://github.com/sgrif/mysqlclient-sys.git", optional = true }
pq-sys = { version = "^0.2.0", optional = true }
quickcheck = { version = "0.3.1", optional = true }
serde_json = { version = ">=0.8.0, <0.10.0", optional = true }
uuid = { version = ">=0.2.0, <0.4.0", optional = true, features = ["use_std"] }

[dev-dependencies]
cfg-if = "0.1.0"
diesel_codegen = "0.10.0"
dotenv = "0.8.0"
quickcheck = "0.3.1"
tempdir = "^0.3.4"

[features]
default = ["with-deprecated"]
unstable = []
large-tables = []
huge-tables = ["large-tables"]
postgres = ["pq-sys"]
sqlite = ["libsqlite3-sys"]
mysql = ["mysqlclient-sys"]
with-deprecated = []
