[package]
name = "diesel_compile_tests"
version = "0.1.0"
authors = ["Sean Griffin <sean@seantheprogrammer.com>"]

[workspace]

[dependencies]
diesel = { path = "../diesel", default-features = false, features = ["extras", "sqlite", "postgres", "mysql", "unstable"] }
compiletest_rs = "=0.3.17"
