[package]
name = "diesel_compile_tests"
version = "0.1.0"

[dependencies]
diesel = { version = "2.0.0-rc.1", default-features = false, features = ["extras", "sqlite", "postgres", "mysql", "with-deprecated"], path = "../diesel" }
trybuild = "1.0.41"

[workspace]
