[package]
name = "diesel_compile_tests"
version = "0.1.0"
edition = "2024"

[dev-dependencies]
ui_test = "0.30"
regex = { version="1.0", default-features = false, features = ["perf", "std", "unicode"] }

[[test]]
name = "compile_tests"
path = "tests/trybuild.rs"
harness = false

[workspace]
