[package]
name = "migrations_internals"
version = "1.4.0"
authors = ["Sean Griffin <sean@seantheprogrammer.com>"]
license = "MIT OR Apache-2.0"
description = "Internal implementation of diesels migration mechanism"
homepage = "https://diesel.rs"

[dependencies]
diesel = { version = "~1.4.0", default-features = false }
barrel = { version = ">= 0.5.0", optional = true, features = ["diesel"] }

[dev-dependencies]
tempfile = "3.0.0"

[features]
default = []
