[package]
name = "diesel_demo_step_3_sqlite"
version = "0.1.0"
license = "MIT OR Apache-2.0"
authors = ["Taryn Hill <taryn@phrohdoh.com>"]

[dependencies]
diesel = { version = "1.4.0", features = ["sqlite"] }
dotenv = "0.10"
