[package]
name = "diesel_demo_step_3_pg"
version = "0.1.0"
authors = ["Sean Griffin <sean@seantheprogrammer.com>"]

[dependencies]
diesel = { version = "1.3.0", features = ["postgres"] }
dotenv = "0.10"
