[package]
name = "getting_started_step_2_pg"
version = "0.1.0"
edition.workspace = true
publish = false

[dependencies]
diesel = { version = "2.2.0", path = "../../../diesel", features = ["postgres"] }
dotenvy = "0.15"

[dev-dependencies]
assert_cmd = "2.0.14"
url = "2.2.2"
diesel_migrations = { version = "2.2.0", path = "../../../diesel_migrations" }

[[bin]]
name = "show_posts_step_2"
path = "src/bin/show_posts.rs"
doc = false

[[bin]]
name = "write_post_step_2"
path = "src/bin/write_post.rs"
doc = false

[lib]
doc = false
