[package]
name = "diesel_infer_schema"
version = "0.1.0"
authors = ["Sean Griffin <sean@seantheprogrammer.com>"]
license = "MIT OR Apache-2.0"
description = "Provides functionality to infer the schema of a database"
documentation = "http://diesel.rs/guides/getting-started"
homepage = "http://diesel.rs"
repository = "https://github.com/diesel-rs/diesel"
keywords = ["orm", "database", "postgres", "postgresql", "sql"]

[dependencies]
diesel = { version = "0.9.0", default-features = false }
syn = "0.10.3"
quote = "0.3.1"

[features]
default = ["postgres"]
postgres = ["diesel/postgres"]
sqlite = ["diesel/sqlite"]
