[package]
name = "getting_started_step_3_mysql"
version = "0.1.0"
edition.workspace = true
publish = false

[dependencies]
diesel = { version = "2.2.0", path = "../../../diesel", features = ["mysql"] }
dotenvy = "0.15"

[dev-dependencies]
assert_cmd = "2.0.14"
url = "2.2.2"
diesel_migrations = { version = "2.2.0", path = "../../../diesel_migrations" }

[[bin]]
name = "show_posts"
doc = false

[[bin]]
name = "write_post"
doc = false

[[bin]]
name = "delete_post"
doc = false

[[bin]]
name = "publish_post"
doc = false

[[bin]]
name = "get_post"
doc = false

[lib]
doc = false
