[package]
name = "diesel_demo_step_3_mysql"
version = "0.1.0"
authors = ["Sean Griffin <sean@seantheprogrammer.com>"]

[dependencies]
diesel = { version = "1.0.0-rc1", features = ["mysql"] }
dotenv = "0.10"
