[package]
name = "diesel_codegen"
version = "0.7.2"
authors = ["Sean Griffin <sean@seantheprogrammer.com>"]

[dependencies]
syn = "0.8.5"
quote = "0.2.1"
diesel = { version = "0.7.1", default-features = false }
diesel_codegen_shared = { path = "../diesel_codegen_shared", default-features = false }

[lib]
proc-macro = true

[features]
default = ["dotenv"]
dotenv = ["diesel_codegen_shared/dotenv"]
postgres = ["diesel_codegen_shared/postgres"]
sqlite = ["diesel_codegen_shared/sqlite"]
