[package]
name = "diesel_codegen"
version = "0.5.2"
authors = ["Sean Griffin <sean@seantheprogrammer.com>"]
license = "MIT OR Apache-2.0"
build = "build.rs"
description = "Annotations to remove boilerplate from Diesel"
documentation = "https://github.com/sgrif/diesel/blob/master/diesel_codegen"
homepage = "http://diesel.rs"
repository = "https://github.com/sgrif/diesel/tree/master/diesel_codegen"
keywords = ["orm", "database", "postgres", "sql", "codegen"]

[build-dependencies]
syntex = { version = ">= 0.28.0, < 0.31.0", optional = true }
syntex_syntax = { version = ">= 0.28.0, < 0.31.0", optional = true }

[dependencies]
syntex = { version = ">= 0.28.0, < 0.31.0", optional = true }
syntex_syntax = { version = ">= 0.28.0, < 0.31.0", optional = true }
diesel = { version = "0.5.0", default-features = false }

[features]
default = ["with-syntex", "postgres"]
nightly = []
with-syntex = ["syntex", "syntex_syntax"]
postgres = ["diesel/postgres"]
sqlite = ["diesel/sqlite"]

[lib]
name = "diesel_codegen"
plugin = true
