[package]
name = "diesel_codegen"
version = "0.6.1"
authors = ["Sean Griffin <sean@seantheprogrammer.com>"]
license = "MIT OR Apache-2.0"
build = "build.rs"
description = "Annotations to remove boilerplate from Diesel"
documentation = "https://github.com/diesel-rs/diesel/blob/master/diesel_codegen"
homepage = "http://diesel.rs"
repository = "https://github.com/diesel-rs/diesel/tree/master/diesel_codegen"
keywords = ["orm", "database", "postgres", "sql", "codegen"]

[build-dependencies]
syntex = { version = ">= 0.37.0, < 0.39.0", optional = true }
syntex_syntax = { version = ">= 0.37.0, < 0.39.0", optional = true }

[dependencies]
syntex = { version = ">= 0.37.0, < 0.39.0", optional = true }
syntex_syntax = { version = ">= 0.37.0, < 0.39.0", optional = true }
diesel = { git = "https://github.com/diesel-rs/diesel.git", default-features = false }

[dev-dependencies]
tempdir = "0.3.4"

[features]
default = ["with-syntex", "postgres"]
nightly = []
with-syntex = ["syntex", "syntex_syntax"]
postgres = ["diesel/postgres"]
sqlite = ["diesel/sqlite"]

[lib]
name = "diesel_codegen"
crate-type = ["rlib", "dylib"]
