[package]
name = "diesel_demo_step_2_mysql"
version = "0.1.0"
authors = ["Sean Griffin <sean@seantheprogrammer.com>"]

[dependencies]
diesel = { version = "1.3.0", features = ["mysql"] }
dotenv = "0.10"
