[package]
name = "all_about_inserts"
version = "0.1.0"
authors = ["Sean Griffin <sean@seantheprogrammer.com>"]

[dependencies]
diesel = { version = "1.4.0", features = ["postgres"] }
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
