[package]
name = "all_about_inserts"
version = "0.1.0"
authors = ["Sage Griffin <sean@seantheprogrammer.com>"]
edition = "2018"

[dependencies]
diesel = { version = "2.0.0-rc.0", path = "../../../diesel", features = ["postgres"] }
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0.68"

[lib]
doc = false
