[package]
name = "sqlite-wasm"
version = "0.1.0"
edition.workspace = true
publish = false

[dependencies]
diesel = { path = "../../../diesel", features = ["sqlite", "returning_clauses_for_sqlite_3_35"] }
diesel_migrations = { path = "../../../diesel_migrations", features = ["sqlite"] }
serde = { version = "1.0.217", features = ["derive"] }
serde-wasm-bindgen = "0.6.5"
wasm-bindgen = "0.2.99"
wasm-bindgen-futures = "0.4.49"

[lib]
crate-type = ["cdylib"]
