[package]
name = "sqlite-wasm-example"
version = "0.1.0"
edition.workspace = true
publish = false

[dependencies]
diesel = { version = "2.3.0", path = "../../../diesel", features = ["sqlite", "returning_clauses_for_sqlite_3_35"] }
diesel_migrations = { path = "../../../diesel_migrations", features = ["sqlite"] }
serde = { version = "1.0.217", features = ["derive"] }
serde-wasm-bindgen = "0.6.5"
wasm-bindgen = "0.2.99"
wasm-bindgen-futures = "0.4.49"

[target.'cfg(all(target_family = "wasm", target_os = "unknown"))'.dependencies]
sqlite-wasm-vfs = "0.1.1"
sqlite-wasm-rs = "0.5.1"

[lib]
crate-type = ["cdylib"]
doc = false
