[package]
name = "diesel_demo"
version = "0.1.0"
authors = ["Sean Griffin <sean@seantheprogrammer.com>"]
build = "build.rs"

[build-dependencies]
syntex = { version = "0.44.0", optional = true }
diesel_codegen_syntex = { version = "0.7.2", features = ["postgres"], optional = true }

[dependencies]
diesel = "0.7.1"
diesel_codegen = { version = "0.7.2", features = ["postgres"], optional = true }
diesel_codegen_old = { path = "../../diesel_codegen_old", features = ["postgres"], optional = true }
dotenv = "0.8.0"

[features]
default = ["nightly"]
with-syntex = ["syntex", "diesel_codegen_syntex"]
nightly = ["diesel/unstable", "diesel_codegen", "diesel_codegen_old"]
