[package]
name = "all_about_inserts_sqlite"
version = "0.1.0"
edition.workspace = true
publish = false

[dependencies]
diesel = { version = "2.3.0", path = "../../../diesel", features = ["sqlite", "chrono", "returning_clauses_for_sqlite_3_35"] }
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0.68"
chrono = { version = "0.4.20", default-features = false, features = ["clock", "std"] }
libsqlite3-sys = { workspace = true, features = ["bundled"] }

[lib]
doc = false
